// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orders.Infrastructure.Persistence;

#nullable disable

namespace Orders.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orders.Domain.Pedidos.LineaPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_producto");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("lineas_pedido", (string)null);
                });

            modelBuilder.Entity("Orders.Domain.Pedidos.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTime?>("FechaCancelacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cancelacion_utc");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaCreacionUtc");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("Orders.Domain.Pedidos.LineaPedido", b =>
                {
                    b.HasOne("Orders.Domain.Pedidos.Pedido", null)
                        .WithMany("Lineas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orders.Domain.Pedidos.Pedido", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
