apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres-catalogo.yaml
  - rabbitmq.yaml
  - jaeger.yaml
  - catalog-api.yaml
  - gateway.yaml
