apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: nexuscommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: nexuscommerce-orders-api:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ConnectionStrings__OrdersDatabase
              value: Host=postgres-orders;Port=5432;Database=nexus_orders;Username=nexus;Password=nexus_dev_password
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: nexuscommerce
spec:
  selector:
    app: orders-api
  ports:
    - port: 8080
      targetPort: 8080
