apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-identidad-datos
  namespace: nexuscommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-identidad
  namespace: nexuscommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-identidad
  template:
    metadata:
      labels:
        app: postgres-identidad
    spec:
      containers:
      - name: postgres
        image: postgres:18-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: nexus_identidad
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: nexuscommerce-secrets
              key: postgres-usuario
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexuscommerce-secrets
              key: postgres-contrasena
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - nexus
            - -d
            - nexus_identidad
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: datos
          mountPath: /var/lib/postgresql
      volumes:
      - name: datos
        persistentVolumeClaim:
          claimName: postgres-identidad-datos
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-identidad
  namespace: nexuscommerce
spec:
  selector:
    app: postgres-identidad
  ports:
  - port: 5432
    targetPort: 5432
