apiVersion: v1
kind: Secret
metadata:
  name: nexuscommerce-secrets
  namespace: nexuscommerce
type: Opaque
stringData:
  postgres-usuario: nexus
  postgres-contrasena: nexus_dev_password
  jwt-clave: NexusCommerce-Development-Key-2026-Muy-Segura-Para-JWT
  rabbitmq-usuario: nexus
  rabbitmq-contrasena: nexus_rabbit_password
